name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BIN: ${{ github.workspace }}/bin
  TMP: ${{ github.temp }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up OS
      run: |
        sudo apt update -y
        sudo apt install -y qemu-utils

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.22"

    - name: Tools
      run: make tools BIN=${{ env.BIN }} TMP=${{ env.TMP }}

    - name: Build
      run: go build -v -race ./...

    - name: Test
      run: go test -exec sudo -v -race ./...
