name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BIN: ${{ github.workspace }}/bin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      -
        name: Set up OS
        run: |
          sudo add-apt-repository ppa:dotnet/backports
          sudo apt update -y
          sudo apt install -y qemu-utils dotnet9

      -
        name: Set up Go
        uses: actions/setup-go@v5

      -
        name: Tools
        run: make tools BIN=${{ env.BIN }}

      -
        name: Build
        run: go build -v -race ./...

      -
        name: Test
        run: go test -exec sudo -v -race -short ./...
