name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BIN: ${{ github.workspace }}/bin

jobs:
  build:
    runs-on: ubuntu:22.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up OS
      run: |
        sudo apt update -y
        sudo apt install -y qemu-utils dotnet6

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.24"

    - name: Tools
      run: make tools BIN=${{ env.BIN }}

    - name: Build
      run: go build -v -race ./...

    - name: Test
      run: go test -exec sudo -v -race ./...
